services:
  - type: web
    name: journal-app-backend
    env: python
    plan: free
    region: oregon
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
      - key: LLM_PROVIDER
        value: groq
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: sqlite:///instance/journal.db
